on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

name: Blogdown Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            blogdown
            tidyverse
            DT
            Rcpp
            htmltools

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Blogdown Site
        run: |
          Rscript -e 'blogdown::build_site(local = FALSE, run_hugo = FALSE, build_rmd = TRUE)'
          hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

